spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://101.201.127.215:3306/devops2025?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8&allowPublicKeyRetrieval=true&connectTimeout=60000&socketTimeout=60000&autoReconnect=true
    username: devops2025
    password: sspku2025
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      # 初始连接数
      initial-size: 5
      # 最小连接池数量
      min-idle: 5
      # 最大连接池数量
      max-active: 10
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      max-evictable-idle-time-millis: 900000
      # 用来检测连接是否有效的sql
      validation-query: SELECT 1
      # 检测连接是否有效的超时时间
      validation-query-timeout: 3
      # 建议配置为true，不影响性能，并且保证安全性
      test-while-idle: true
      # 申请连接时执行validationQuery检测连接是否有效
      test-on-borrow: false
      # 归还连接时执行validationQuery检测连接是否有效
      test-on-return: false
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计
      filters: stat,wall
      # WebStatFilter配置
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      # StatViewServlet配置（Druid监控页面）
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: admin123
        allow:
        deny:


# MyBatis 配置
mybatis:
  mapper-locations: classpath:mapper/*.xml  # Mapper XML 文件位置
  type-aliases-package: com.example.demo.app.entity  # 实体类包路径，简化 XML 中的类型引用
  configuration:
    map-underscore-to-camel-case: true  # 数据库下划线字段自动映射为 Java 驼峰属性
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 打印 SQL 语句到控制台

server:
  port: 8080
  servlet:
    context-path: /usermanagement
